// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjlD5WfmBcTCtBv6BlvQFlH4qSquaN14',
    appId: '1:410639022131:web:ed9287d1c9b7b2caf08b46',
    messagingSenderId: '410639022131',
    projectId: 'newsapp-50b17',
    authDomain: 'newsapp-50b17.firebaseapp.com',
    storageBucket: 'newsapp-50b17.appspot.com',
    measurementId: 'G-6FQFHMYF94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCxardhJOlz4Iquz1ri9MdbD6vLcDkMUM',
    appId: '1:410639022131:android:6ad0a9e569ae58fbf08b46',
    messagingSenderId: '410639022131',
    projectId: 'newsapp-50b17',
    storageBucket: 'newsapp-50b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2JjH86VTxXQPMIQ6c8KhhIw8TLElFGw',
    appId: '1:410639022131:ios:14343f349d3564c7f08b46',
    messagingSenderId: '410639022131',
    projectId: 'newsapp-50b17',
    storageBucket: 'newsapp-50b17.appspot.com',
    iosBundleId: 'com.example.newwwsProj',
  );
}
